ignore_theme_config: true # 4.0+的jekyll，如果有key没有覆盖，会合并主题的config。因为自定义的内容很多，故关闭
# remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: aqua

# GitHub Pages默认启用了一些且无法禁用；本地安装主题会自动安装依赖插件，但远程主题必须手动设置，但Pages有白名单
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-paginate
  # - jekyll-gist


# 用户信息
locale:              zh-CN
title:               谭九鼎的博客 # 网页标题的一部分
name:                谭九鼎 # 页脚
repository:          imba-tjd/blog # 正确设置才可使用site.github对象（但无法在本yml中用），会自动设置url、baseurl、title、description
logo:                https://avatars.githubusercontent.com/imba-tjd?s=40&v=4 # 网页中的title的左边的图，不是favicon
# description: # 默认会自动使用仓库的tagline
# url: https://blog.imba-tjd.tech # 如果站点用了虚拟路径，还要设置baseurl

author:
  name   : 谭九鼎
  avatar : https://avatars.githubusercontent.com/imba-tjd
  bio    : 一只普通的计算机爱好者。
  location: China
  links: # footer也可以加links
    - label: Website
      icon: "fas fa-fw fa-link"
      url: https://imba-tjd.tech
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/imba-tjd
    - label: 知乎
      icon: "fab fa-fw fa-zhihu"
      url: https://www.zhihu.com/people/tan-jiu-ding/activities
    - label: Steam
      icon: "fab fa-fw fa-steam"
      url: https://steamcommunity.com/id/imba-tjd
social:
  name:  imba-tjd
  links:
    - https://github.com/imba-tjd
    - https://www.zhihu.com/people/tan-jiu-ding/activities


# 默认只包含.htaccess，如果手动设置，include和keep_files不会包含默认值，但exclude却会包含，是jekyll4的新功能
include: [_pages]
exclude: # 默认排除Gemfile和lock、node_modules、一部分vendor下的内容、以点开头的、以下划线开头的（如果没有collection）
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - vendor
  - LICENSE
  - Readme.md
  - CNAME
# keep_files: # 生成时保留哪些内容，默认会保留.git和.svn；还可添加.nojekyll、Readme


# Outputting
strict_front_matter: true
# breadcrumbs: true
search: true
search_full_content: true
permalink: /:categories/:title # 默认是date
# permalink: /:slugified_categories/:title # jekyll 4.1才支持，把类别里的空格变为横杠，当然还是全小写的
paginate: 7 # amount of posts to show
# paginate_path: /page:num #【默】
timezone: Asia/Shanghai
# lsi: true # 为相关的文章生成索引；好像需要classifier-reborn插件，但没有时也没报错；mm中是关掉的，默认关闭


# Sass/SCSS
sass:
  # sass_dir: _sass
  style: compressed # 默认没开
# HTML Compression；开启后inline js注释需用/* */而不能用//否则会出问题
compress_html:
  clippings: all
  ignore:
    envs: development
# JS
# footer_scripts: # 一旦手动设置，就会覆盖mm中条目，因此要补上main；head_scripts和after_footer_scripts不受影响
  # - /assets/js/main.min.js
  # - 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/js/all.min.js" async defer type="text/javascript'
# 自定义HTTP头
# webrick:
#   headers:
#     My-Header: My-Value
#     My-Other-Header: My-Other-Value


# Archives
category_archive:
  type: liquid # 可改为jekyll-archives
  path: /categories
# tag_archive:
#   type: liquid
#   path: /tags
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# 默认的Front Matter
defaults:
  # _posts
  - scope:
      path: "" # 不限
      type: posts # 对应collection，默认还自带pages和drafts两种类型，jekyll-archives还会生成tag和category类型
    values:
      layout: single
      # author_profile: true
      read_time: true # 还可设置words_per_minute
      # comments: true # 还需配置comments的provider等，mm默认支持Disqus和utterances（使用GitHub的issue）
      # share: true # 分享到FB、Twitter、Linkedin
      related: true
      toc: true # 还有toc_sticky: true
      category: uncategoried


# Markdown Processing
# markdown: GFM # 只有GitHub Pages下才有效；默认kramdown
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter_opts:
#     css_class: 'highlight'
#     span:
#       line_numbers: false
#     block:
#       line_numbers: false
#       #start_line: 1
# 以下是默认值
# kramdown:
#   auto_ids          : true
#   entity_output     : as_char
#   toc_levels        : [1, 2, 3, 4, 5, 6]
#   smart_quotes      : lsquo,rsquo,ldquo,rdquo
#   input             : GFM
#   hard_wrap         : false
#   footnote_nr       : 1
#   show_warnings     : false


# Reference:
#   - https://github.com/iBug/iBug-source/blob/master/_config.yml
#   - https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
#   - https://github.com/iBug/iBug-source/commit/24b88418ae0c954788755bf191568ac322b1ac4d
#   - https://jekyllrb.com/docs/configuration/default/ （默认值）
